# Generated by Django 6.0.5 on 2026-10-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_babyinformation_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="babyinformation",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("", "未知"), ("1", "男"), ("2", "女")],
                default="",
                max_length=2,
            ),
        ),
    ]
